class AppLocalization {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'login': 'Login',
      'register': 'Register',
      'email': 'Email Address',
      'password': 'Password',
      'username': 'Username',
      'create_account': 'CREATE NEW ACCOUNT',
      'join_cluck': 'JOIN CLUCKTOGETHER',
      'player_profile': 'Create your player profile',
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'username_required': 'Username is required',
      'authenticating': 'AUTHENTICATING...',
      'creating': 'CREATING...',
      'games': 'Games',
      'social': 'Social',
      'message': 'Messages',
      'profile': 'Profile',
      'settings': 'Settings',
      'customize_ui': 'Customize Interface',
      'customize_ui_desc': 'Change app colors & theme presets',
      'win_rate': 'WIN RATE',
      'games_played': 'GAMES',
      'friends': 'FRIENDS',
      'edit_profile': 'Edit Profile',
      'achievements': 'Achievements',
      'coins': 'Coins',
      'logout': 'Logout',
      'select_theme': 'Select Theme Template',
      'select_bg': 'Background Style',
      'select_lang': 'Language',
      'preview': 'Preview',
      'preview_desc': 'This is how elements will look with your settings.',
      'save_settings': 'Save Settings',
      'theme_saved': 'Settings saved successfully',
      'cancel': 'Cancel',
      'save': 'Save',
      'login_failed': 'Login failed',
      'register_failed': 'Registration failed',
      'coop_desc': 'Play & connect in the coop',
      'not_logged_in': 'Not logged in',
      'theme_mode': 'Theme Mode',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'eggHatch': 'Egg Hatch',
      'cozyCoop': 'Cozy Coop',
      'fluffyCloud': 'Fluffy Cloud',
      'sweetMint': 'Sweet Mint',
    },
    'vi': {
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'email': 'Địa chỉ Email',
      'password': 'Mật khẩu',
      'username': 'Tên người dùng',
      'create_account': 'TẠO TÀI KHOẢN MỚI',
      'join_cluck': 'THAM GIA CLUCKTOGETHER',
      'player_profile': 'Tạo hồ sơ người chơi của bạn',
      'email_required': 'Vui lòng nhập Email',
      'password_required': 'Vui lòng nhập Mật khẩu',
      'username_required': 'Vui lòng nhập Tên người dùng',
      'authenticating': 'ĐANG XÁC THỰC...',
      'creating': 'ĐANG TẠO...',
      'games': 'Trò chơi',
      'social': 'Cộng đồng',
      'message': 'Tin nhắn',
      'profile': 'Hồ sơ',
      'settings': 'Cài đặt',
      'customize_ui': 'Tùy chỉnh giao diện',
      'customize_ui_desc': 'Thay đổi màu sắc & chủ đề ứng dụng',
      'win_rate': 'TỶ LỆ THẮNG',
      'games_played': 'SỐ TRẬN',
      'friends': 'BẠN BÈ',
      'edit_profile': 'Sửa hồ sơ',
      'achievements': 'Thành tựu',
      'coins': 'Xu',
      'logout': 'Đăng xuất',
      'select_theme': 'Chọn bộ giao diện phối sẵn',
      'select_bg': 'Phong cách nền',
      'select_lang': 'Ngôn ngữ',
      'preview': 'Xem trước',
      'preview_desc': 'Đây là cách giao diện hiển thị với cài đặt của bạn.',
      'save_settings': 'Lưu cài đặt',
      'theme_saved': 'Đã lưu cài đặt thành công',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'login_failed': 'Đăng nhập thất bại',
      'register_failed': 'Đăng ký thất bại',
      'coop_desc': 'Chơi & kết nối trong chuồng gà',
      'not_logged_in': 'Chưa đăng nhập',
      'theme_mode': 'Chế độ giao diện',
      'dark_mode': 'Chế độ tối',
      'light_mode': 'Chế độ sáng',
      'eggHatch': 'Màu Trứng Nhỏ',
      'cozyCoop': 'Chuồng Gà Ấm Áp',
      'fluffyCloud': 'Mây Bồng Bềnh',
      'sweetMint': 'Bạc Hà Ngọt Ngào',
    },
  };

  static String getString(String langCode, String key) {
    final langMap = _localizedValues[langCode] ?? _localizedValues['en']!;
    return langMap[key] ?? key;
  }
}
